#diccionario con informacion de usuarios

info_usuarios:
  - { nombre: pepe,
      password: 123456, 
      priv: ALL, 
      db: db10, 
      objs: public, 
      type: schema,
      grant_option: false }
