---

- name: Incluir instalacion centos8
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Incluir instalacion Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

...
