---

- name: Añadir repositorio postgresql Rhel8
  ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"


- name: Instalar gnupg
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"


- name: Agregar clave GPG de postgresql Debian
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: ansible_distribution == "Debian"


- name: Añadir repositorio postgresql Debian
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main
    state: present
  when: ansible_distribution == "Debian"

...
