---

- name: Añadir repositorio postgresql Centos8
  ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true


- name: Instalar postgresql y psycopg2
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes_centos8 }}"


- name: Inicializar postgresql
  ansible.builtin.command:
    cmd: postgresql-setup initdb
  register: ini_postgres
  failed_when: ini_postgres.changed == "false"
  changed_when: false


- name: Iniciar servicio postgresql
  ansible.builtin.service:
    state: started
    name: postgresql
    enabled: true

...
